import { Integration } from './types';

export const INITIAL_INTEGRATIONS: Integration[] = [
    {
        id: '1',
        name: 'Slack',
        description: "Automate notifications and alerts directly into your team's channels.",
        iconName: 'forum',
        iconBgColor: 'bg-[#4A154B]',
        categories: ['Communication', 'Productivity'],
        isConnected: true,
        autoSync: true,
    },
    {
        id: '2',
        name: 'Google Workspace',
        description: 'Seamlessly sync calendars, drive files, and user directories.',
        iconName: 'workspaces',
        iconBgColor: 'bg-white',
        customIconColor: 'text-slate-800',
        hasGradientOverlay: true,
        categories: ['Productivity'],
        isConnected: false,
    },
    {
        id: '3',
        name: 'Microsoft Teams',
        description: 'Centralize team collaboration, meetings, and file sharing workflows.',
        iconName: 'groups',
        iconBgColor: 'bg-[#5059C9]',
        categories: ['Communication', 'Productivity'],
        isConnected: true,
        autoSync: true,
    },
    {
        id: '4',
        name: 'Zoom',
        description: 'Generate meeting links automatically for interviews and events.',
        iconName: 'videocam',
        iconBgColor: 'bg-[#2D8CFF]',
        categories: ['Communication'],
        isConnected: false,
    },
    {
        id: '5',
        name: 'QuickBooks',
        description: 'Sync payroll and accounting data effortlessly.',
        iconName: 'account_balance',
        iconBgColor: 'bg-[#2CA01C]',
        categories: ['Payroll', 'Productivity'],
        isConnected: false,
    },
    {
        id: '6',
        name: 'Gusto',
        description: 'Sync employee payroll data, benefits, and tax documents.',
        iconName: 'account_balance_wallet',
        iconBgColor: 'bg-[#F45D48]',
        categories: ['Payroll'],
        isConnected: true,
        lastSync: '2m ago',
        autoSync: true,
    },
];
